import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'packages/contracts/src/generated/**',
      'project plan/**',
      // Generated by `next build` and marked "should not be edited". Its triple-slash
      // references are how Next.js wires its own types; linting it only ever produces
      // an error nobody is allowed to fix.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        __dirname: 'readonly',
        module: 'writable',
        require: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/consistent-type-imports': 'off',
      'no-console': 'off',

      // ADR-0006: no binary floating point for money. `parseFloat`/`Number()` on a
      // monetary string is the single most common way that rule gets broken.
      'no-restricted-globals': [
        'error',
        { name: 'parseFloat', message: 'ADR-0006: money is decimal. Use @acct/domain Money.' },
      ],
    },
  },
  {
    // Test files may use `any` freely when asserting on raw driver output.
    files: ['**/*.test.ts', '**/*.spec.ts', '**/testing/**'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
  prettier,
);
