-- =============================================================================
-- 0022 — Permission registry seed (GENERATED — pnpm contracts:permissions)
-- =============================================================================
-- ADR-0005 §3 / F-016 / F-207. Rows are derived from x-permission and
-- x-additional-permissions in contracts/openapi.yaml. Do not hand-edit: contract
-- check 13 compares this seed against the contract and fails on any difference.
--
-- 193 permission(s), 19 of them high-risk.
-- =============================================================================

INSERT INTO permissions (code, resource, action, description, is_high_risk, requires_reauth, min_phase) VALUES
  ('account.create', 'account', 'create', 'Routes: POST /accounts', false, false, 2),
  ('account.edit', 'account', 'edit', 'Routes: PATCH /accounts/{id}', false, false, 2),
  ('account.view', 'account', 'view', 'Routes: GET /accounts', false, false, 2),
  ('accounting_book.view', 'accounting_book', 'view', 'Routes: GET /accounting-books', false, false, 1),
  ('accounting_period.hard_close', 'accounting_period', 'hard_close', 'Routes: POST /accounting-periods/{id}/hard-close', false, false, 1),
  ('accounting_period.reopen', 'accounting_period', 'reopen', 'Routes: POST /accounting-periods/{id}/reopen', true, true, 1),
  ('accounting_period.soft_close', 'accounting_period', 'soft_close', 'Routes: POST /accounting-periods/{id}/soft-close', false, false, 1),
  ('accounting_period.view', 'accounting_period', 'view', 'Routes: GET /accounting-periods', false, false, 1),
  ('accounting_policy.configure', 'accounting_policy', 'configure', 'Routes: POST /accounting-policies', false, false, 1),
  ('accounting_policy.view', 'accounting_policy', 'view', 'Routes: GET /accounting-policies', false, false, 1),
  ('ai.approve_action', 'ai', 'approve_action', 'Routes: POST /ai/actions/{id}/approve, POST /ai/actions/{id}/reject', true, true, 8),
  ('ai.extract', 'ai', 'extract', 'Routes: POST /ai/documents/extract', false, false, 8),
  ('ai.query', 'ai', 'query', 'Routes: POST /ai/questions', false, false, 8),
  ('ai.suggest', 'ai', 'suggest', 'Routes: POST /ai/coding/suggest, POST /ai/reconciliation/suggest', false, false, 8),
  ('ai.view', 'ai', 'view', 'Routes: GET /ai/anomalies', false, false, 8),
  ('approval.approve', 'approval', 'approve', 'Routes: POST /approval-tasks/{id}/approve, POST /approval-tasks/{id}/reject, POST /approval-tasks/{id}/request-changes', false, false, 6),
  ('approval.delegate', 'approval', 'delegate', 'Routes: POST /approval-tasks/{id}/delegate', false, false, 6),
  ('approval.view', 'approval', 'view', 'Routes: GET /approval-tasks', false, false, 6),
  ('ar.write_off', 'ar', 'write_off', 'Routes: POST /ar/write-offs', true, true, 3),
  ('asset.capitalize', 'asset', 'capitalize', 'Routes: POST /assets/{id}/capitalize', false, false, 5),
  ('asset.create', 'asset', 'create', 'Routes: POST /assets', false, false, 5),
  ('asset.depreciate', 'asset', 'depreciate', 'Routes: POST /assets/depreciation-runs', false, false, 5),
  ('asset.dispose', 'asset', 'dispose', 'Routes: POST /assets/{id}/dispose', false, false, 5),
  ('asset.impair', 'asset', 'impair', 'Routes: POST /assets/{id}/impair, POST /assets/{id}/reverse-impairment', false, false, 5),
  ('asset.revalue', 'asset', 'revalue', 'Routes: POST /assets/{id}/revalue', false, false, 5),
  ('asset.transfer', 'asset', 'transfer', 'Routes: POST /assets/{id}/transfer', false, false, 5),
  ('asset.view', 'asset', 'view', 'Routes: GET /assets', false, false, 5),
  ('audit.manage', 'audit', 'manage', 'Routes: POST /audit-requests', false, false, 6),
  ('audit.view', 'audit', 'view', 'Routes: GET /audit-events, GET /audit-requests', false, false, 1),
  ('bank_account.create', 'bank_account', 'create', 'Routes: POST /bank-accounts', false, false, 4),
  ('bank_account.view', 'bank_account', 'view', 'Routes: GET /bank-accounts', false, false, 4),
  ('bank_connection.manage', 'bank_connection', 'manage', 'Routes: POST /bank-connections', false, false, 4),
  ('bank_connection.view', 'bank_connection', 'view', 'Routes: GET /bank-connections', false, false, 4),
  ('bank_rule.manage', 'bank_rule', 'manage', 'Routes: POST /bank-rules', false, false, 4),
  ('bank_rule.view', 'bank_rule', 'view', 'Routes: GET /bank-rules', false, false, 4),
  ('bank_transfer.create', 'bank_transfer', 'create', 'Routes: POST /bank-transfers', false, false, 4),
  ('bank.categorize', 'bank', 'categorize', 'Routes: POST /bank-transactions/{id}/categorize, POST /bank-transactions/{id}/split', false, false, 4),
  ('bank.import', 'bank', 'import', 'Routes: POST /bank-accounts/{id}/imports', false, false, 4),
  ('bank.reconcile', 'bank', 'reconcile', 'Routes: POST /bank-reconciliations, GET /bank-reconciliations, POST /bank-reconciliations/{id}/complete +1 more', false, false, 4),
  ('bank.reconcile_reopen', 'bank', 'reconcile_reopen', 'Routes: POST /bank-reconciliations/{id}/reopen', true, true, 4),
  ('bank.sync', 'bank', 'sync', 'Routes: POST /bank-accounts/{id}/sync', false, false, 4),
  ('bank.view', 'bank', 'view', 'Routes: GET /bank-transactions, GET /bank-transactions/{id}/matches, GET /cash-position', false, false, 4),
  ('branch.create', 'branch', 'create', 'Routes: POST /branches', false, false, 1),
  ('branch.view', 'branch', 'view', 'Routes: GET /branches', false, false, 1),
  ('budget.approve', 'budget', 'approve', 'Routes: POST /budgets/{id}/approve', false, false, 5),
  ('budget.create', 'budget', 'create', 'Routes: POST /budgets', false, false, 5),
  ('budget.revise', 'budget', 'revise', 'Routes: POST /budgets/{id}/revise', false, false, 5),
  ('budget.view', 'budget', 'view', 'Routes: GET /budget-control/check, GET /budgets, GET /budgets/{id}/variance', false, false, 5),
  ('close.finalize', 'close', 'finalize', 'Routes: POST /close-runs/{id}/finalize', false, false, 6),
  ('close.manage', 'close', 'manage', 'Routes: POST /close-checklists/generate, POST /close-runs, POST /close-tasks/{id}/complete', false, false, 6),
  ('close.view', 'close', 'view', 'Routes: GET /close-runs, GET /close-runs/{id}/tasks', false, false, 6),
  ('consolidation.finalize', 'consolidation', 'finalize', 'Routes: POST /consolidation-runs/{id}/finalize', false, false, 7),
  ('consolidation.manage', 'consolidation', 'manage', 'Routes: POST /consolidation-groups', false, false, 7),
  ('consolidation.run', 'consolidation', 'run', 'Routes: POST /consolidation-runs, POST /consolidation-runs/{id}/eliminate, POST /consolidation-runs/{id}/translate', false, false, 7),
  ('consolidation.view', 'consolidation', 'view', 'Routes: GET /consolidation-groups, GET /consolidation-runs', false, false, 7),
  ('credit_note.create', 'credit_note', 'create', 'Routes: POST /credit-notes', false, false, 3),
  ('credit_note.view', 'credit_note', 'view', 'Routes: GET /credit-notes', false, false, 3),
  ('currency.view', 'currency', 'view', 'Routes: GET /currencies', false, false, 1),
  ('customer_receipt.allocate', 'customer_receipt', 'allocate', 'Routes: POST /customer-receipts/{id}/allocate', false, false, 3),
  ('customer_receipt.create', 'customer_receipt', 'create', 'Routes: POST /customer-receipts', false, false, 3),
  ('customer_receipt.view', 'customer_receipt', 'view', 'Routes: GET /customer-receipts', false, false, 3),
  ('customer_refund.create', 'customer_refund', 'create', 'Routes: POST /customer-refunds', false, false, 3),
  ('customer.create', 'customer', 'create', 'Routes: POST /customers', false, false, 3),
  ('customer.view', 'customer', 'view', 'Routes: GET /customers, GET /customers/{id}/statement', false, false, 3),
  ('dimension.create', 'dimension', 'create', 'Routes: POST /dimension-values, POST /dimensions', false, false, 2),
  ('dimension.view', 'dimension', 'view', 'Routes: GET /dimension-values, GET /dimensions', false, false, 2),
  ('dunning.view', 'dunning', 'view', 'Routes: GET /dunning-cases', false, false, 3),
  ('einvoice.submit', 'einvoice', 'submit', 'Routes: POST /einvoice/{id}/submit', false, false, 3),
  ('exchange_rate.manage', 'exchange_rate', 'manage', 'Routes: POST /exchange-rates', false, false, 1),
  ('exchange_rate.override', 'exchange_rate', 'override', 'Supply a manual rate that overrides the provider rate. doc 11 requires a permission and an audit reason; exchange_rates.override_reason is NOT NULL when is_manual_override.', false, false, 1),
  ('exchange_rate.view', 'exchange_rate', 'view', 'Routes: GET /exchange-rates', false, false, 1),
  ('expense_claim.create', 'expense_claim', 'create', 'Routes: POST /expense-claims', false, false, 3),
  ('expense_claim.view', 'expense_claim', 'view', 'Routes: GET /expense-claims', false, false, 3),
  ('file.create', 'file', 'create', 'Routes: POST /files/{id}/complete, POST /files/upload-url', false, false, 3),
  ('file.delete', 'file', 'delete', 'Routes: DELETE /files/{id}', false, false, 3),
  ('file.view', 'file', 'view', 'Routes: GET /files/{id}', false, false, 3),
  ('fiscal_year.create', 'fiscal_year', 'create', 'Routes: POST /fiscal-years', false, false, 1),
  ('fiscal_year.view', 'fiscal_year', 'view', 'Routes: GET /fiscal-years', false, false, 1),
  ('forecast.manage', 'forecast', 'manage', 'Routes: POST /forecasts', false, false, 5),
  ('forecast.view', 'forecast', 'view', 'Routes: GET /forecasts', false, false, 5),
  ('fx.remeasure', 'fx', 'remeasure', 'Routes: POST /fx-remeasurement-runs', false, false, 7),
  ('goods_receipt.create', 'goods_receipt', 'create', 'Routes: POST /goods-receipts', false, false, 3),
  ('goods_receipt.view', 'goods_receipt', 'view', 'Routes: GET /goods-receipts', false, false, 3),
  ('integration.manage', 'integration', 'manage', 'Routes: POST /integrations/{id}/connect, POST /integrations/{id}/disconnect', true, true, 9),
  ('integration.sync', 'integration', 'sync', 'Routes: POST /integrations/{id}/sync', false, false, 9),
  ('integration.view', 'integration', 'view', 'Routes: GET /integrations', false, false, 9),
  ('inventory.adjust', 'inventory', 'adjust', 'Routes: POST /inventory/adjustments, POST /inventory/landed-costs', false, false, 5),
  ('inventory.count', 'inventory', 'count', 'Routes: POST /inventory/counts', false, false, 5),
  ('inventory.issue', 'inventory', 'issue', 'Routes: POST /inventory/issues', false, false, 5),
  ('inventory.receive', 'inventory', 'receive', 'Routes: POST /inventory/receipts', false, false, 5),
  ('inventory.transfer', 'inventory', 'transfer', 'Routes: POST /inventory/transfers', false, false, 5),
  ('inventory.view', 'inventory', 'view', 'Routes: GET /inventory/on-hand, GET /inventory/valuation', false, false, 5),
  ('invoice.approve', 'invoice', 'approve', 'Routes: POST /invoices/{id}/approve', false, false, 3),
  ('invoice.create', 'invoice', 'create', 'Routes: POST /invoices, POST /recurring-invoices', false, false, 3),
  ('invoice.edit_draft', 'invoice', 'edit_draft', 'Routes: PATCH /invoices/{id}', false, false, 3),
  ('invoice.post', 'invoice', 'post', 'Routes: POST /invoices/{id}/post', false, false, 3),
  ('invoice.send', 'invoice', 'send', 'Routes: POST /invoices/{id}/send', false, false, 3),
  ('invoice.view', 'invoice', 'view', 'Routes: GET /invoices, GET /invoices/{id}, GET /recurring-invoices', false, false, 3),
  ('invoice.void', 'invoice', 'void', 'Routes: POST /invoices/{id}/void-or-credit', false, false, 3),
  ('item.create', 'item', 'create', 'Routes: POST /items', false, false, 5),
  ('item.view', 'item', 'view', 'Routes: GET /items', false, false, 5),
  ('journal.approve', 'journal', 'approve', 'Routes: POST /journals/{id}/approve', false, false, 2),
  ('journal.create', 'journal', 'create', 'Routes: POST /journals, POST /recurring-journals', false, false, 2),
  ('journal.post', 'journal', 'post', 'Routes: POST /journals/{id}/post', true, true, 2),
  ('journal.post_control', 'journal', 'post_control', 'Post a manual journal to a control account. One of doc 02''s seven high-risk permissions.', true, true, 2),
  ('journal.post_to_adjustment_period', 'journal', 'post_to_adjustment_period', 'Name an adjustment period explicitly instead of the period resolve_accounting_period() derives from posting_date (F-403).', false, false, 2),
  ('journal.reverse', 'journal', 'reverse', 'Routes: POST /journals/{id}/reverse', false, false, 2),
  ('journal.submit', 'journal', 'submit', 'Routes: POST /journals/{id}/submit', false, false, 2),
  ('journal.view', 'journal', 'view', 'Routes: POST /accounting-events/simulate, GET /journals, GET /journals/{id} +1 more', false, false, 2),
  ('ledger.view', 'ledger', 'view', 'Routes: GET /ledger/accounts/{id}/activity', false, false, 2),
  ('legal_entity.configure', 'legal_entity', 'configure', 'Routes: PATCH /legal-entities/{id}, POST /legal-entities/{id}/activate', false, false, 1),
  ('legal_entity.create', 'legal_entity', 'create', 'Routes: POST /legal-entities', false, false, 1),
  ('legal_entity.view', 'legal_entity', 'view', 'Routes: GET /legal-entities, GET /legal-entities/{id}', false, false, 1),
  ('localization.install', 'localization', 'install', 'Routes: POST /legal-entities/{id}/localization/install', true, true, 3),
  ('localization.view', 'localization', 'view', 'Routes: GET /localizations', false, false, 3),
  ('migration.cutover', 'migration', 'cutover', 'Routes: POST /migration-jobs/{id}/cutover', true, true, 9),
  ('migration.import', 'migration', 'import', 'Routes: POST /migration-jobs/{id}/import', false, false, 9),
  ('migration.manage', 'migration', 'manage', 'Routes: POST /migration-jobs, POST /migration-jobs/{id}/upload, POST /migration-jobs/{id}/validate', false, false, 9),
  ('migration.view', 'migration', 'view', 'Routes: GET /migration-jobs, GET /migration-jobs/{id}/reconciliation', false, false, 9),
  ('number_sequence.configure', 'number_sequence', 'configure', 'Routes: POST /number-sequences', false, false, 1),
  ('number_sequence.view', 'number_sequence', 'view', 'Routes: GET /number-sequences', false, false, 1),
  ('organization.configure', 'organization', 'configure', 'Routes: PATCH /organizations/{id}', false, false, 1),
  ('organization.create', 'organization', 'create', 'Routes: POST /organizations', false, false, 1),
  ('organization.view', 'organization', 'view', 'Routes: GET /organizations, GET /organizations/{id}, GET /settings/effective', false, false, 1),
  ('payment_run.approve', 'payment_run', 'approve', 'Routes: POST /payment-runs/{id}/approve', true, true, 3),
  ('payment_run.create', 'payment_run', 'create', 'Routes: POST /payment-runs', false, false, 3),
  ('payment_run.execute', 'payment_run', 'execute', 'Routes: POST /payment-runs/{id}/execute', true, true, 3),
  ('payment_run.view', 'payment_run', 'view', 'Routes: GET /payment-runs', false, false, 3),
  ('platform.entitlement', 'platform', 'entitlement', 'Routes: GET /admin/entitlements', false, false, 1),
  ('platform.feature_flag', 'platform', 'feature_flag', 'Routes: GET /admin/feature-flags', false, false, 0),
  ('platform.support_grant', 'platform', 'support_grant', 'Routes: POST /admin/support-grants', true, true, 1),
  ('platform.tenant_manage', 'platform', 'tenant_manage', 'Routes: POST /admin/tenants/{id}/reactivate, POST /admin/tenants/{id}/suspend', true, true, 1),
  ('platform.tenant_view', 'platform', 'tenant_view', 'Routes: GET /admin/tenants', false, false, 1),
  ('project.bill', 'project', 'bill', 'Routes: POST /projects/{id}/billing-proposals', false, false, 5),
  ('project.create', 'project', 'create', 'Routes: POST /projects', false, false, 5),
  ('project.view', 'project', 'view', 'Routes: GET /projects', false, false, 5),
  ('purchase_order.approve', 'purchase_order', 'approve', 'Routes: POST /purchase-orders/{id}/approve', false, false, 3),
  ('purchase_order.create', 'purchase_order', 'create', 'Routes: POST /purchase-orders', false, false, 3),
  ('purchase_order.view', 'purchase_order', 'view', 'Routes: GET /purchase-orders', false, false, 3),
  ('purchase_requisition.create', 'purchase_requisition', 'create', 'Routes: POST /purchase-requisitions', false, false, 3),
  ('purchase_requisition.view', 'purchase_requisition', 'view', 'Routes: GET /purchase-requisitions', false, false, 3),
  ('quote.create', 'quote', 'create', 'Routes: POST /quotes', false, false, 3),
  ('quote.edit', 'quote', 'edit', 'Routes: POST /quotes/{id}/accept', false, false, 3),
  ('quote.view', 'quote', 'view', 'Routes: GET /quotes', false, false, 3),
  ('reconciliation.certify', 'reconciliation', 'certify', 'Routes: POST /account-reconciliations/{id}/certify', false, false, 6),
  ('reconciliation.manage', 'reconciliation', 'manage', 'Routes: POST /account-reconciliations', false, false, 6),
  ('reconciliation.view', 'reconciliation', 'view', 'Routes: GET /account-reconciliations', false, false, 6),
  ('report.export', 'report', 'export', 'Routes: POST /report-runs', true, true, 6),
  ('report.manage', 'report', 'manage', 'Routes: POST /report-definitions', false, false, 6),
  ('report.snapshot', 'report', 'snapshot', 'Routes: POST /financial-statement-snapshots', false, false, 6),
  ('report.view', 'report', 'view', 'Routes: GET /financial-statement-snapshots, GET /report-definitions, GET /report-runs +12 more', false, false, 2),
  ('role.manage', 'role', 'manage', 'Routes: POST /memberships, POST /roles, PATCH /roles/{id}', true, true, 1),
  ('role.view', 'role', 'view', 'Routes: GET /permissions, GET /roles', false, false, 1),
  ('sales_order.create', 'sales_order', 'create', 'Routes: POST /sales-orders', false, false, 3),
  ('sales_order.view', 'sales_order', 'view', 'Routes: GET /sales-orders', false, false, 3),
  ('session.revoke', 'session', 'revoke', 'Routes: POST /sessions/{id}/revoke', false, false, 1),
  ('session.view', 'session', 'view', 'Routes: GET /sessions', false, false, 1),
  ('task.complete', 'task', 'complete', 'Routes: POST /tasks/{id}/complete', false, false, 6),
  ('task.view', 'task', 'view', 'Routes: GET /tasks', false, false, 6),
  ('tax_code.manage', 'tax_code', 'manage', 'Routes: POST /tax-codes, POST /tax-rates', false, false, 3),
  ('tax_code.view', 'tax_code', 'view', 'Routes: GET /tax-codes, GET /tax-rates', false, false, 3),
  ('tax_return.approve', 'tax_return', 'approve', 'Routes: POST /tax-returns/{id}/approve', false, false, 3),
  ('tax_return.create', 'tax_return', 'create', 'Routes: POST /tax-returns', false, false, 3),
  ('tax_return.file', 'tax_return', 'file', 'Routes: POST /tax-returns/{id}/mark-filed', true, true, 3),
  ('tax_return.prepare', 'tax_return', 'prepare', 'Routes: POST /tax-returns/{id}/prepare', false, false, 3),
  ('tax_return.view', 'tax_return', 'view', 'Routes: GET /tax-returns', false, false, 3),
  ('tax.calculate', 'tax', 'calculate', 'Routes: POST /tax/calculate', false, false, 3),
  ('tax.override', 'tax', 'override', 'Replace the determined tax code on a line, writing a tax_overrides row with a reason. One of doc 02''s seven high-risk permissions.', true, true, 3),
  ('tax.view', 'tax', 'view', 'Routes: GET /tax-transactions', false, false, 3),
  ('user.invite', 'user', 'invite', 'Routes: POST /users/invite', false, false, 1),
  ('user.suspend', 'user', 'suspend', 'Routes: POST /users/{id}/reactivate, POST /users/{id}/suspend', false, false, 1),
  ('user.view', 'user', 'view', 'Routes: GET /memberships, GET /users', false, false, 1),
  ('vendor_bill.approve', 'vendor_bill', 'approve', 'Routes: POST /vendor-bills/{id}/approve', false, false, 3),
  ('vendor_bill.create', 'vendor_bill', 'create', 'Routes: POST /vendor-bills', false, false, 3),
  ('vendor_bill.match', 'vendor_bill', 'match', 'Routes: POST /vendor-bills/{id}/match', false, false, 3),
  ('vendor_bill.override_duplicate', 'vendor_bill', 'override_duplicate', 'Accept a bill that duplicate detection flagged. vendor_bills.duplicate_override_reason is NOT NULL whenever duplicate_override_by is set (F-020).', false, false, 3),
  ('vendor_bill.post', 'vendor_bill', 'post', 'Routes: POST /vendor-bills/{id}/post', false, false, 3),
  ('vendor_bill.view', 'vendor_bill', 'view', 'Routes: GET /vendor-bills', false, false, 3),
  ('vendor_credit.create', 'vendor_credit', 'create', 'Routes: POST /vendor-credits', false, false, 3),
  ('vendor_credit.view', 'vendor_credit', 'view', 'Routes: GET /vendor-credits', false, false, 3),
  ('vendor_payment.allocate', 'vendor_payment', 'allocate', 'Routes: POST /vendor-payments/{id}/allocate', false, false, 3),
  ('vendor_payment.pay', 'vendor_payment', 'pay', 'Routes: POST /vendor-payments', true, true, 3),
  ('vendor_payment.view', 'vendor_payment', 'view', 'Routes: GET /vendor-payments', false, false, 3),
  ('vendor.change_bank_details', 'vendor', 'change_bank_details', 'Routes: PATCH /vendors/{id}/bank-details', true, true, 3),
  ('vendor.create', 'vendor', 'create', 'Routes: POST /vendors', false, false, 3),
  ('vendor.view', 'vendor', 'view', 'Routes: GET /vendors', false, false, 3),
  ('warehouse.create', 'warehouse', 'create', 'Routes: POST /warehouses', false, false, 5),
  ('warehouse.view', 'warehouse', 'view', 'Routes: GET /warehouses', false, false, 5),
  ('webhook.manage', 'webhook', 'manage', 'Routes: POST /webhook-endpoints', false, false, 9),
  ('webhook.replay', 'webhook', 'replay', 'Routes: POST /webhook-deliveries/{id}/replay', false, false, 9),
  ('webhook.view', 'webhook', 'view', 'Routes: GET /webhook-deliveries, GET /webhook-endpoints', false, false, 9),
  ('workflow.manage', 'workflow', 'manage', 'Routes: POST /approval-workflows, POST /approval-workflows/{id}/publish', false, false, 6),
  ('workflow.view', 'workflow', 'view', 'Routes: GET /approval-workflows', false, false, 6);
